server:
  port: 8101 #���ж˿ں�
spring:
  application:
    name: eureka-client #��������
eureka:
  client:
    register-with-eureka: true #ע�ᵽEureka��ע������
    fetch-registry: true #��ȡע��ʵ���б�
    service-url:
      defaultZone: http://localhost:8001/eureka/ #����ע�����ĵ�ַ
